### ISSUE TITLE
Add links to slides in the ReadMe

### ISSUE THREAD

**Issue by spcanelon** [rladies-eastlansing/2022-accessible_dataviz#1]
Hello! I came here from twitter to take a look at the slides prior to the meetup tonight but couldn't get to them. Could you please include the direct links in the ReadMe so they are easy to find?

I tried using this link to access Andrea's slides, for example, and it didn't point to the rendered html: https://rladies-eastlansing.github.io/2022-accessible_dataviz/AndreaGV/Andrea-RLadies_EastLansing.html

(original html file is at https://github.com/rladies-eastlansing/2022-accessible_dataviz/blob/main/AndreaGV/Andrea-RLadies_EastLansing.html)

I wonder if GitHub Pages needs to be enabled for this repo?

**Comment by jananiravi** [comment]
Thanks for the note, Silvia! I have now added the links for both presentations + code to the `README` file.

**Comment by spcanelon** [comment]
Thank you @jananiravi !
